project:
  type: book
  output-dir: docs

book:
  title: "Muliple Regression"
  author: "Cristian Mesquida"
  date: "11/16/2025"
  chapters:
    - index.qmd
    - recap.qmd
    - mr_1.qmd
    - mr_2.qmd
    - mr_3.qmd
    - mr_4.qmd

format:
  html:
   toc: true
   toc-location: right
   number-sections: true
   code-link: true
   theme:
      - cosmo
      - brand
   single-file: true
editor: visual

