project:
  type: book

book:
  title: "Muliple Regression"
  author: "Cristian Mesquida"
  date: "11/16/2025"
  chapters:
    - index.qmd
    - lectures/lecture_1.qmd
    - lectures/lecture_2.qmd
    - lectures/lecture_3.qmd
    - lectures/lecture_4.qmd

format:
  html:
   toc: true
   toc-location: right
   number-sections: true
   code-link: true
   theme:
      - cosmo
      - brand
   single-file: true
editor: visual

